server:
  port: 8081

spring:
  mail:
    host: smtp.gmail.com
    username: trung03trung@gmail.com
    password: yhzztttnihpqlclt
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/document?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: trung0000


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeout: 60

application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000

